name: Release (production)
on:
  push:
    # Matching on any tags which is a production release versioning
    # Matching:
    #  - v1.0.0
    #  - v1.1.0
    #  - v2.1.13
    #
    # Ignoring:
    #  - v1.0.0-beta5
    #  - v1.0.1-rc3
    #  - v2.1.4-hotfix-87
    tags:
      - 'v*'
      - '!v*-*'

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        cd cmds
        make
      env:
        GO111MODULE: on

    - name: Collecting files
      run: |
        scripts/collect.sh ${{ github.workspace }}/archive

    - name: Uploading flist (${{ github.ref }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        action: publish
        user: tf-autobuilder
        root: archive
        token: ${{ secrets.HUB_JWT }}
        name: test-${{ github.ref }}.flist
    
    - name: Rename flist from test-${{ github.ref }}.flist to test:${{ github.ref }}.flist
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: rename
        user: tf-autobuilder
        name: test-${{ github.ref }}.flist
        target: test:${{ github.ref }}.flist
    
    - name: Symlink flist (development)
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-test
        name: test:development:latest.flist
        target: tf-autobuilder/test:${{ github.ref }}.flist
    
    - name: Symlink flist (testing)
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-test
        name: test:testing:latest.flist
        target: tf-autobuilder/test:${{ github.ref }}.flist

    - name: Symlink flist (production)
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-test
        name: test:production:latest.flist
        target: tf-autobuilder/test:${{ github.ref }}.flist

