name: Zos Update Worker

defaults:
  run:
    working-directory: tools/test-update-worker 

on: 
  push:
    paths:
      - tools/test-update-worker/**
  pull_request:
    paths:
      - tools/test-update-worker/**

jobs:
  Explore-Packge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose
          working-directory: tools/test-update-worker 

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          working-directory: tools/test-update-worker 
        env:
          GO111MODULE: on

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
          gofmt-path: "tools/test-update-worker"
       
      - name: Test
        run: go test -v ./...
  

