name: Update Worker Release

defaults:
  run:
    working-directory: tools/test-update-worker

on:
  push:
    tags:
      - "v*"

jobs:
  test-update-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build test update worker
        run: |
          make build

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset for test update worker
        id: upload-release-asset-worker
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: tools/test-update-worker/bin/test-update-worker
          asset_name: test-update-worker
          asset_content_type: application/x-pie-executable
